- name: Setup Ansible Control Node
  hosts: control
  become: true # Privilege escalation for setting up the Control Node
  become_method: sudo # Privilege escalation for setting up the Control Node
  roles:
    - control-node-setup
...