- name: Setup Ansible Control Node
  hosts: control
  become: true # Privilege escalation for setting up the Control Node
  become_method: sudo # Privilege escalation for setting up the Control Node
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install necessary tools
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Add Ansible PPA repository
      apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name : Install Ansible
      apt:
        name: ansible
        state: present
    
    - name: Gather Ansible version
      setup:
        filter: "ansible_version"

    - name: Display Ansible version
      debug:
        msg: "Installed Ansible version: {{ ansible_version.full }}"
...