---
- name: Create AWS Infrastructure
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/aws.yml
    - ../vars/vault.yml
  roles:
    - vpc
    - control-node
    - worker-node
    - database
