---
- name: Create AWS Infrastructure
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/aws.yaml
    - vars/vault.yaml
    - vars/global.yaml
  roles:
    - vpc
    - control-node
    - worker-node
    - database
    - alb
...