---
- name: Copy pem EC2 key
  hosts: localhost
  vars_files:
    - vars/aws.yaml
  tasks:
    - name: Copy
      ansible.builtin.copy:
        src: /home/{{ ansible_user }}/{{ ec2.key_name }}
        dest: /home/{{ ansible_user }}
        mode: '0400'

- name: Generate SSH key and distribute it to worker nodes
  hosts: control
  tasks:
    - name: Check if SSH key already exists
      stat:
        path: /home/{{ ansible_user }}/.ssh/id_rsa
      register: ssh_key_check

    - name: Generate new SSH key if not present
      command: ssh-keygen -t rsa -b 2048 -f /home/{{ ansible_user }}/.ssh/id_rsa -N ""
      args:
        creates: /home/{{ ansible_user }}/.ssh/id_rsa
      when: not ssh_key_check.stat.exists

- name: Copy SSH key to worker nodes
  hosts: control
  vars_files:
    - vars/aws.yaml
    - vars/global.yaml
  tasks:
    - name: Install SSH public key using ssh-copy-id
      shell: ssh-agent bash -c "ssh-add /home/{{ ansible_user }}/{{ ec2.key_name }}; ssh-copy-id -i /home/{{ ansible_user }}/.ssh/id_rsa.pub {{ ansible_user }}@{{ item }}
      args:
        executable: /bin/bash
      register: ssh_copy_result
      loop: "{{ workers_list }}"
...