---

- name: Create a target group
  community.aws.elb_target_group:
    name: "ansible-tg"
    protocol: http
    port: 80
    vpc_id: "{{ vpc.vpc.id }}"
    targets:
      - Id: "{{ ec2_worker_nodes.results[0].instance_ids[0] }}"
        Port: 80
      - Id: "{{ ec2_worker_nodes.results[1].instance_ids[0] }}"
        Port: 80
    state: present
  register: tg

- amazon.aws.elb_application_lb:
    name: "ansible-alb"
    security_groups:
      - "{{ alb_sg.group_id }}"
    subnets:
      - "{{ public_subnets.results[0].subnet.id }}"
      - "{{ public_subnets.results[1].subnet.id }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward 
            TargetGroupName: "{{ tg.target_group_name }}"
    state: present
  register: alb

...