---
- name: Create EC2 Worker Node
  amazon.aws.ec2_instance:
    name: "ansible-worker-node"
    instance_type: "{{ ec2.instance_type }}"
    image_id: "{{ ec2.ami_id }}"
    vpc_subnet_id: "{{ item.subnet.id }}"
    region: "{{ aws_region }}"
    key_name: "{{ aws_ec2_key_pair.key.name }}"
    security_group: "{{ app_sg.group_id }}"
    state: present
  loop: "{{  app_subnets.results }}"
  register: ec2_worker_nodes
...