---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    state: present
    name: ansible-playbook-vpc
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ aws_region }}"
  register: vp
- name: Create an Internet Gateway to connect VPC to Internet
  community.aws.ec2_vpc_igw:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
  register: ig
- name: Create Public Subnet
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnets.public.cidr }}"
    region: "{{ aws_region }}"
    map_public: yes
  register: public_subne
- name: Create App Subnets
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnets.app.cidr }}"
    region: "{{ aws_region }}"
  register: app_subne
- name: Create DB Subnets
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ subnets.db.cidr }}"
    region: "{{ aws_region }}"
  register: db_subne
- name: Create Public Route Table
  amazon.aws.ec2_vpc_route_table:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    subnets:
      - "{{ public_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: public_route_tabl
- name: Create NAT Gateway Elastic IP
  amazon.aws.ec2_eip:
      state: present
      region: "{{ aws_region }}"
  register: nat_ei
- name: Create NAT Gateway
  amazon.aws.ec2_vpc_nat_gateway:
    subnet_id: "{{ public_subnet.subnet.id }}"
    allocation_id: "{{ nat_eip.allocation_id }}"
    state: present
    region: "{{ aws_region }}"
  register: nat_gatewa
- name: Create App Route Table
  amazon.aws.ec2_vpc_route_table:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    subnets:
      - "{{ app_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gateway.nat_gateway_id }}"
    region: "{{ aws_region }}"
  register: app_route_tabl
- name: Create DB Route Table
  amazon.aws.ec2_vpc_route_table:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    subnets:
      - "{{ db_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gateway.nat_gateway_id }}"
    region: "{{ aws_region }}"
  register: db_route_tabl
- name: Create Control Node Security Group
  amazon.aws.ec2_security_group:
    state: present
    name: control-node-sg
    description: "Control Node Security Group"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
  register: control_node_s
- name: Create App Security Group
  amazon.aws.ec2_security_group:
    state: present
    name: app-sg
    description: "App Security Group"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
          - 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports:
          - 22
        group_id: "{{ control_node_sg.group_id }}"
  register: app_s
- name: Create DB Security Group
  amazon.aws.ec2_security_group:
    state: present
    name: app-sg
    description: "Database Security Group"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
          - 3306
        group_id: "{{ app_sg.group_id }}"
  register: db_sg
...